version: '3.7'

services:
  api:
    build: .
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: kvstore
      DB_USER: root
      DB_PASSOWRD: root

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kvstore
    volumes:
      - ./data:/var/lib/mysql
